import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import path from "path";
import fs from "fs";
import matter from "gray-matter";
import { getBloggdata } from "@/lib/getBloggdata";
import { useParams } from 'next/navigation'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,params
}: Readonly<{
  children: React.ReactNode;
  params:any
}>) {
  function getBloggdata({ slug }: { slug: string }) {
    const markdownFile = fs.readFileSync(
      path.join("blogdata", slug + ".mdx"),
      "utf-8"
    );
    const { data: frontMatter, content } = matter(markdownFile);

    return {
      frontMatter,
      slug,
      content,
    };
  }


  console.log(params)

  return (
    <html lang="en">
      <body className={inter.className}>
      
        {children}
      </body>
    </html>
  );
}
